version: '3'

services:
    db:
        image: nginx
        volumes:
            - "./html:/usr/share/nginx/html"
            # - "./images:/usr/share/nginx/html/images"
            - "./config/nginx.conf:/etc/nginx/nginx.conf"
            - "./config/error.log:/etc/nginx/logs/error.log"
            - "./config/mime.types:/etc/nginx/conf/mime.types"
            - "./config/proxy.conf:/etc/nginx/proxy.conf"
            - "./config/fastcgi.conf:/etc/nginx/fastcgi.conf"
            - "./config/access.log:/etc/nginx/logs/access.log"
        ports:
            - "80:80"